### ISSUE TITLE
Add support for Angular 14 and 15

### ISSUE THREAD

**Issue by Barzille** [Karelics/angular-unleash-proxy-client#1]
Hi is it possible to add versions which work also with Angular 14 and 15?

**Comment by yuri-karelics** [comment]
Hi @Barzille, unfortunately we have no versions exactly for Angular 14-15, we started from 16. But 14-15 also support 'standalone' feature we are using in our directives, so you can try to install our package (version 16 for example) with '--legacy-peer-deps' flag

**Comment by yuri-karelics** [comment]
my bad, we started from Angular 15 :) So, just use our NPM package with version 15.1 (we use major version of our package similar to Angular version)
